apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cd-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - bindings:
      - ref: cd-binding
      template:
        ref: cd-template
