apiVersion: v1
kind: PersistentVolume
metadata:
  name: skills-network-volume
  labels:
    type: local
spec:
  storageClassName: skills-network-learner
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"