---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: base-pipeline
spec:
  params:
    - name: repository
      description: The git repository to process
      default: https://github.com/rofrano/tekton-testing.git
    - name: branch
      description: The branch to clone
      default: master
  tasks:
    - name: clone
      taskRef:
        name: echo
      params:
      - name: message
        value: "Cloning $(params.branch) from repository: $(params.repository)..."

    - name: lint
      taskRef:
        name: echo
      params:
      - name: message
        value: "Calling Flake8 linter..."
      runAfter:
        - clone

    - name: tests
      taskRef:
        name: echo
      params:
      - name: message
        value: "Running unit tests with PyUnit..."
      runAfter:
        - lint

    - name: deploy
      taskRef:
        name: echo
      params:
      - name: message
        value: "Deploying $(params.branch) branch of $(params.repository) ..."
      runAfter:
        - tests
