apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  params:
    - name: message
      description: The message to echo
      type: string
  steps:
    - name: echo-message
      image: alpine:3
      command: [echo]
      args: ["$(params.message)"]

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: list-files
spec:
  params:
    - name: folder
      description: The folder to list
      type: string
  steps:
    - name: ls
      image: alpine:3
      command: [ls]
      args: ["$(params.folder)"]
