---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  params:
    - name: project
      default: tekton-ci-demo
  tasks:
    - name: checkout
      taskRef:
        name: echo
      params:
      - name: message
        value: git clone git@github.com:$(params.project)
    - name: lint
      taskRef:
        name: list-files
      runAfter:
        - checkout
    - name: tests
      taskRef:
        name: echo
      params:
      - name: message
        value: Running unit tests here...
      runAfter:
        - lint
    - name: deploy
      taskRef:
        name: echo
      params:
      - name: message
        value: "Deploying $(params.project) to development environment"
      runAfter:
        - tests
