---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  workspaces:
  - name: pipeline-workspace
  params:
  - name: repository
    default: https://github.com/rofrano/tekton-testing.git
  - name: branch
    default: master
  tasks:
    - name: clone
      workspaces:
        - name: artifacts
          workspace: pipeline-workspace          
      taskRef:
        name: clone-repo
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)

    - name: lint
      workspaces:
        - name: task-workspace
          workspace: pipeline-workspace
      taskRef:
        name: linting
      runAfter:
        - clone

    - name: run-tests
      workspaces:
        - name: artifacts
          workspace: pipeline-workspace          
      taskRef:
        name: run-tests
      runAfter:
        - lint

    # - name: deploy
    #   taskRef:
    #     name: echo
    #   params:
    #   - name: message
    #     value: "Deploying $(params.project) to development environment"
    #   runAfter:
    #     - tests
