---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repo
spec:
  workspaces:
  - name: artifacts
  params:
    - name: repository
      description: the git repository
    - name: branch
      description: the git branch
      default: master
  steps:
    - name: clone
      image: ibmcom/pipeline-base-image
      command: ["/bin/bash", "-c"]
      args:
        - |
          WS=$(workspaces.artifacts.path)
          REPOSITORY=$(inputs.params.repository)
          BRANCH=$(inputs.params.branch)
          cd $WS
          git --version
          git clone --single-branch --branch $BRANCH $REPOSITORY
          ls $WS

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
spec:
  workspaces:
  - name: artifacts
  steps:
    - name: nosetests
      # image: ibmcom/pipeline-base-image
      image: python:3.9-slim
      command: ["/bin/bash", "-c"]
      args:
        - |
          WS=$(workspaces.artifacts.path)/tekton-testing
          cd $WS
          pwd
          ls -l
          pip install -r requirements.txt
          echo "********** RUNNING TESTS **********"
          nosetests
          ls $WS

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  params:
    - name: message
      description: The message to echo
      type: string
  steps:
    - name: echo-message
      image: alpine:3
      command: [echo]
      args: ["$(params.message)"]

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: list-files
spec:
  steps:
    - name: ls
      image: alpine:3
      command: [ls]
      args: ["/"]
