# Need to add https://github.com/tektoncd/catalog.git to Toolchain
# Also add task/git-clone/0.7 to Pipeline
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  params:
    - name: message
      description: The message to echo
      type: string
  steps:
    - name: echo-message
      image: alpine:3
      command: [echo]
      args: ["$(params.message)"]
