---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: env
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: environment
    - name: properties
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: list-files
      params:
      - name: folder
        value: "/workspace/properties"
