---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: apikey
      description: The api key provided by customer
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: env
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: environment
    - name: echo
      taskRef:
        name: echo
      params:
      - name: message
        value: "The API Key is: $(params.apikey)"
    - name: properties
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: list-files
      params:
      - name: folder
        value: "/workspace/properties"
