# Need to add https://github.com/tektoncd/catalog.git to Toolchain
# Also add task/git-clone/0.7 to Pipeline
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  params:
    - name: message
      description: The message to echo
      type: string
  steps:
    - name: echo-message
      image: alpine:3
      command: [echo]
      args: ["$(params.message)"]
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: list-files
spec:
  workspaces:
    - name: output
  params:
    - name: folder
      description: The folder to list
      type: string
  steps:
    - name: ls
      image: alpine:3
      command: [ls]
      args: ["$(params.folder)"]
      volumeMounts:
      - name: properties
        mountPath: "/workspace/properties"
    - name: cat
      image: alpine:3
      command: [cat]
      args: ["$(params.folder)/apikey"]
      volumeMounts:
      - name: properties
        mountPath: "/workspace/properties"
  volumes:
  - name: properties
    projected:
      sources:
      - configMap:
          name: default-properties
          optional: true
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: environment
spec:
  workspaces:
    - name: output
  steps:
    - name: env
      image: alpine:3
      command: [env]
      env:
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              name: default-properties
              key: apikey
